### Default URL
GET http://localhost:5000/

### Default API URL
GET http://localhost:5000/api/

//***** USER *****//

### getAllUser API URL
GET http://localhost:5000/api/users/

### getUserById API URL
GET http://localhost:5000/api/user/618d9e7e32456040a8f3250c

### Default updateUser URL
PUT http://localhost:5000/api/updateUser/618d6fcde8bdae86415cad58
content-type: application/json

{
    "first_name": "Jules"
}

### addUser API URL
POST http://localhost:5000/api/addUser/
content-type: application/json

{
    "first_name": "Patrik",
    "last_name": "Legrand",
    "email": "sait-kik@hotmail.com",
    "username": "Test",
    "password": "test2"
}

### Default removeContact URL
DELETE http://localhost:5000/api/removeUser/618d6fcde8bdae86415cad58

//***** COLUMN *****//

### getAllColumn API URL
GET http://localhost:5000/api/columns

### getColumnById API URL
GET http://localhost:5000/api/column/:id

### addColumn API URL
POST http://localhost:5000/api/addColumn/
content-type: application/json

{
    "title": "Column test",
    "index": 0,
    "maxTask": 10,
    "_tasks": ["618d6fcde8bdae86415cad58","618d6fcde8bdae86415cad58"]
}

### Default updateColumn URL
PUT http://localhost:5000/api/updateColumn/6195122b3c5dd1819f182277
content-type: application/json

{
    "title": "Jules",
    "index": 10,
    "maxTask": 1
}

### Default removeColumn URL
DELETE http://localhost:5000/api/removeColumn/6195122b3c5dd1819f182277

//***** LOG *****//

### getAllLog API URL
GET http://localhost:5000/api/logs/

### getLogById API URL
GET http://localhost:5000/api/log/61951d853d935eb947113033

### addLog API URL
POST http://localhost:5000/api/addLog/
content-type: application/json

{
    "_userId": "618d6fcde8bdae86415cad58",
    "_columnIdStart": "61951d1d3d935eb947113029",
    "_columnIdEnd": "61951d4a3d935eb94711302d",
    "updated_at": "2020-11-17"
}

### Default updateLog URL
PUT http://localhost:5000/api/updateLog/61951d853d935eb947113033
content-type: application/json

{
    "_columnIdStart": "61951d4a3d935eb94711302d",
    "_columnIdEnd": "61951d1d3d935eb947113029",
    "updated_at": "2020-11-18"
}

### Default removeLog URL
DELETE http://localhost:5000/api/removeLog/61951d853d935eb947113033


# PROJECTS

### Get all projects
GET http://localhost:5000/api/projects/


### getProjectById API URL
GET http://localhost:5000/api/projects/619d165aab62e0388fdbfac7

### add project
POST http://localhost:5000/api/addProject/
content-type: application/json

{
    "title": "PPPE"
}

#### Default updateProject URL
PUT http://localhost:5000/api/updateProject/619d165aab62e0388fdbfac7
content-type: application/json

{
    "title": "Test"
}

### Default removeProject URL
DELETE http://localhost:5000/api/removeProject/619a9dd68616a2e8d5c083db


### create sprint
POST http://localhost:5000/api/addSprint/619d165aab62e0388fdbfac7
content-type: application/json

{
    "title": "Sprint 0"
}


### get one sprint from project
GET http://localhost:5000/api/project/619d16a52002c0630d0f9364/sprint/619d29510d3b3e78a6c4812f