### Default URL
GET http://localhost:5000/

### Default API URL
GET http://localhost:5000/api/

//***** USER *****//

### getAllUser API URL
GET http://localhost:5000/api/users/

### getUserById API URL
GET http://localhost:5000/api/user/618d6fcde8bdae86415cad58

### Default updateUser URL
PUT http://localhost:5000/api/updateUser/618d6fcde8bdae86415cad58
content-type: application/json

{
    "first_name": "Jules"
}

### addUser API URL
POST http://localhost:5000/api/addUser/
content-type: application/json

{
    "first_name": "Contact Added",
    "last_name": "Test",
    "email": "sait-kik@hotmail.com",
    "username": "Test",
    "password": "test2"
}

### Default removeContact URL
DELETE http://localhost:5000/api/removeUser/618d66474ae5b330a9331d7c

//***** COLUMN *****//

### getAllColumn API URL
GET http://localhost:5000/api/columns/

### getColumnById API URL
GET http://localhost:5000/api/column/:id

### addColumn API URL
POST http://localhost:5000/api/addColumn/
content-type: application/json

{
    "title": "Column test",
    "index": 0,
    "maxTask": 10,
    "_tasks": ["618d6fcde8bdae86415cad58","618d6fcde8bdae86415cad58"]
}

### Default updateColumn URL
PUT http://localhost:5000/api/updateColumn/6195122b3c5dd1819f182277
content-type: application/json

{
    "title": "Jules",
    "index": 10,
    "maxTask": 1
}

### Default removeColumn URL
DELETE http://localhost:5000/api/removeColumn/6195122b3c5dd1819f182277