### getAllColumn API URL
GET http://localhost:5000/api/columns

### getColumnById API URL
GET http://localhost:5000/api/column/:id

### addColumn API URL
POST http://localhost:5000/api/addColumn/
content-type: application/json

{
	"title": "Column",
	"index": 0,
	"maxTask": 10,
	"_tasks": ["618d6fcde8bdae86415cad58","618d6fcde8bdae86415cad58"]
}

### Default updateColumn URL
PUT http://localhost:5000/api/updateColumn/6195122b3c5dd1819f182277
content-type: application/json

{
	"title": "Jules",
	"index": 10,
	"maxTask": 1
}

### Default removeColumn URL
DELETE http://localhost:5000/api/removeColumn/6195122b3c5dd1819f182277


### Add task to column
POST http://localhost:5000/api/column/61a9e17854812dd4f4de2a6b/addTask/618d6fcde8bdae86415cad58

