# PROJECTS

### Get all projects
GET http://localhost:5000/api/projects/

### getProjectById API URL
GET http://localhost:5000/api/projects/61a50f7e3fc2fc80f0f3aa2c

### add project
POST http://localhost:5000/api/addProject/
content-type: application/json

{
	"title": "Cest la bonne"
}

#### Default updateProject URL
PUT http://localhost:5000/api/updateProject/61a50f243fc2fc80f0f3aa17
content-type: application/json

{
	"title": "C'est la bonne"
}

### Default removeProject URL
DELETE http://localhost:5000/api/removeProject/61a50f243fc2fc80f0f3aa17

### create sprint
POST http://localhost:5000/api/project/61a119531b96b6b9ed9671a3/addSprint
content-type: application/json

{
	"title": "Sprint wallah"
}

### get one sprint from project
GET http://localhost:5000/api/project/61a119531b96b6b9ed9671a3/sprint/61a147788dcf29c044112e46

###delete one sprint from project 
DELETE http://localhost:5000/api/project/619d16a52002c0630d0f9364/delete_sprint/619e5cdb2b46f4c047513490

########################################################################################################

### Create task in an existing project
POST http://localhost:5000/api/project/61a50f7e3fc2fc80f0f3aa2c/addTask
content-type: application/json

{
	"title": "Task bonne"
}

### Get task from an existing project
GET http://localhost:5000/api/project/61a50f7e3fc2fc80f0f3aa2c/task/61a50fb73fc2fc80f0f3aa30

### Get all tasks from an existing project
GET http://localhost:5000/api/project/61a50f7e3fc2fc80f0f3aa2c/tasks

##############################################################################################################
