# PROJECTS

### Get all projects
GET http://localhost:5000/api/projects/

### getProjectById API URL
GET http://localhost:5000/api/project/61a549f275a713f1150e7188

### add project
POST http://localhost:5000/api/addProject/
content-type: application/json

{
	"title": "projet 2"
}

#### Default updateProject URL
PUT http://localhost:5000/api/updateProject/61a522cdc300c6cce45eb37e
content-type: application/json

{
	"title": "Test"
}

### Default removeProject URL
DELETE http://localhost:5000/api/removeProject/61a522cdc300c6cce45eb37e

#################################################################################
#Sprints

### create sprint
POST http://localhost:5000/api/project/61a549f275a713f1150e7188/addSprint
content-type: application/json

{
	"title": "Sprint 2 test WEB"
}

### get one sprint from project
GET http://localhost:5000/api/project/61a549f275a713f1150e7188/sprint/61a54d27d5b2ff27be5821cb


### get all sprints from project
GET http://localhost:5000/api/project/61a549f275a713f1150e7188/sprints/


###delete one sprint from project 
DELETE http://localhost:5000/api/project/61a549f275a713f1150e7188/delete-sprint/61a54d27d5b2ff27be5821cb

########################################################################################################
#tasks

### Create task in an existing project
POST http://localhost:5000/api/project/61a549f275a713f1150e7188/addTask
content-type: application/json

{
	"title": "Task 1 test WEB"
}

### Get task from an existing project
GET http://localhost:5000/api/project/61a549f275a713f1150e7188/task/61a54db7d5b2ff27be5821d9

### Get all tasks from an existing project
GET http://localhost:5000/api/project/61a549f275a713f1150e7188/tasks

### delete a task from an existing project
DELETE http://localhost:5000/api/project/61a549f275a713f1150e7188/delete-task/61a610e9884f0e4d9ab6c632

##############################################################################################################
