#########################################################################""
# PROJECTS

### Get all projects
GET http://localhost:5000/api/projects/

### getProjectById API URL
GET http://localhost:5000/api/projects/61a549d075a713f1150e7179

### add project
POST http://localhost:5000/api/addProject/
content-type: application/json

{
	"title": "Projet 2"
}

#### Default updateProject URL
PUT http://localhost:5000/api/updateProject/61a535204f44870c04ed025d
content-type: application/json

{
	"title": "Projet 2"
}

### Default removeProject URL
DELETE http://localhost:5000/api/removeProject/61a6417b0334c5f023c28ac3


#################################################################################
#SPRINT

### create sprint
POST http://localhost:5000/api/project/61a535a04f44870c04ed026e/addSprint
content-type: application/json

{
	"title": "Sprint TEST 4"
}

### get one sprint from project
GET http://localhost:5000/api/project/61a53939896e0b50815fc764/sprint/61a53f5fbec8e97a93c9176c



###delete one sprint from project 
DELETE http://localhost:5000/api/project/61a53939896e0b50815fc764/delete_sprint/61a53f5fbec8e97a93c9176c

########################################################################################################
#TASK


### Create task in an existing project
POST http://localhost:5000/api/project/61a549d075a713f1150e7179/addTask
content-type: application/json

{
	"title": "Task pour voir si getTasksFromProject fonctionne"
}

### Get task from an existing project
GET http://localhost:5000/api/project/61a53939896e0b50815fc764/task/61a53d4036181a4b21bba761


### Get all tasks from an existing project
GET http://localhost:5000/api/project/61a549d075a713f1150e7179/tasks

##############################################################################################################