//***** TASK *****//
### Get all tasks 
GET http://localhost:5000/api/tasks/

### Get task by id
GET http://localhost:5000/api/task/61a4f99459b6e946680356f7

### Add task
POST http://localhost:5000/api/addTask/
content-type: application/json

{
	"title": "premiere tache wallah",
	"color": "rouge",
	"description": "ceci est la premiere tache, c'est un test",
	"state": "a faire"
}

### Remove a task
DELETE http://localhost:5000/api/removeTask/619ec4c87d5b5c528be8e823
