//***** TASK *****//
### Get all tasks 
GET http://localhost:5000/api/tasks/

### Get task by id
GET http://localhost:5000/api/task/61b65decd7222816c7f42be0

### Add task
POST http://localhost:5000/api/add-task/
content-type: application/json

{
	"title": "tache test owner",
	"color": "rouge",
	"description": "ceci est la premiere tache, c'est un test",
	"state": "a faire",
	"_owner": "blank"
}

### Remove a task
DELETE http://localhost:5000/api/removeTask/61a52cb7df9572abed26401e

### Update task
PUT http://localhost:5000/api/updateTask/61a6c50cdd7a0f2ccf0989b7
content-type: application/json

{
	"title": "ok",
	"color": "ook",
	"description": "okkkk",
	"state": "okkkkkkk"
}